### ISSUE TITLE
undesirable projection results

### ISSUE THREAD

**Issue by ligengen** [taeinkwon/PyHoloAssist#2]
1. When finding the corresponding RGB frame from the video, the calculation of frame timestamp needs accurate fps. But ffprobe-python does not give the correct fps. 
2. `1/frame_rate` might introduce floating point error. To have more accurate timestamps, it can be replaced with rational number calculation.
#1

**Comment by taeinkwon** [comment]
Hi @ligengen , 

Thank you for your report. I merged your PR into the main branch.
